version: '3'
services:
  password:
    build: 
      context: ./src/Services/Password
      dockerfile: Dockerfile
    ports: 
      - 5002:8080
    networks:
      - the-host-br-network
    container_name: the-host-password-container
  auth:
    build: 
      context: ./src/Services/Auth
      dockerfile: Dockerfile
    ports: 
      - 5001:8080
    networks:
      - the-host-br-network
    container_name: the-host-auth-container
  mongo:
    image: "mongo"
    ports: 
      - 27017:27017
    networks:
      - the-host-br-network
    container_name: the-host-mongo-container
networks:
  the-host-br-network:
    driver: bridge