version: '3'
services:
  password:
    build: 
      context: ./src/Services/Password
      dockerfile: Dockerfile
    ports: 
      - 5002:8080
    networks:
      - the-host-br-network
  auth:
    build: 
      context: ./src/Services/Auth
      dockerfile: Dockerfile
    ports: 
      - 5001:8080
    networks:
      - the-host-br-network
networks:
  the-host-br-network:
    driver: bridge