version: '3'
services:
  web:
   image: tugkanmeral/the-host-web:latest
   build: 
     context: ./src/Web/the-host-blazor-wasm
     dockerfile: Dockerfile
   ports: 
     - 8000:80
   networks:
     - the-host-br-network
   container_name: the-host-blazor-wasm-container

  auth:
    image: tugkanmeral/the-host-auth
    build: 
      context: ./src/Services/Auth
      dockerfile: Dockerfile
    ports: 
      - 5001:8080
    networks:
      - the-host-br-network
    container_name: the-host-auth-container

  password:
    image: tugkanmeral/the-host-password
    build: 
      context: ./src/Services/Password
      dockerfile: Dockerfile
    ports: 
      - 5002:8080
    networks:
      - the-host-br-network
    container_name: the-host-password-container

  note:
    image: tugkanmeral/the-host-note
    build: 
      context: ./src/Services/Note
      dockerfile: Dockerfile
    ports: 
      - 5003:8080
    networks:
      - the-host-br-network
    container_name: the-host-note-container

  user:
    image: tugkanmeral/the-host-user
    build: 
      context: ./src/Services/User
      dockerfile: Dockerfile
    ports: 
      - 5004:8080
    networks:
      - the-host-br-network
    container_name: the-host-user-container

  mongo:
    image: "mongo"
    ports: 
      - 27017:27017
    networks:
      - the-host-br-network
    container_name: the-host-mongo-container
    volumes:
      - './data:/data/db'
networks:
  the-host-br-network:
    driver: bridge